# Changes here will be overwritten by Copier
_commit: v0.3.5-6-g39b9909
_src_path: ./python-project-template/
email: e.dorta@tudelft.nl
environment_manager: uv
full_name: Era Dorta
host: github.com
license: GPL
min_python_version: '3.12'
org: Era-Dorta
project_name: python-template-uv-example
project_short_description: A great package.
url: https://github.com/Era-Dorta/python-template-uv-example
